In [61]:
import pandas as pd
import numpy as np

In [62]:
data = {
    "calories":[220, 300, 400],
    "duration":[40, 45, 55]
}

df = pd.DataFrame(data)
df

   calories  duration
0       220        40
1       300        45
2       400        55

In [63]:
data = {
    "name": ["alice","charlie", "david", "bob"],
    "age": [35, 24, 55, 40],
    "city": ['NYC', 'LA', 'NYC', 'chicago'],
    "salary": [70000, 75000, 80000, 70000 ]
}
df = pd.DataFrame(data)

In [64]:
df

      name  age     city  salary
0    alice   35      NYC   70000
1  charlie   24       LA   75000
2    david   55      NYC   80000
3      bob   40  chicago   70000

In [65]:
df.head(2)

      name  age city  salary
0    alice   35  NYC   70000
1  charlie   24   LA   75000

In [66]:
df.shape

(4, 4)

In [67]:
df.columns

Index(['name', 'age', 'city', 'salary'], dtype='str')

In [68]:
df.describe()

             age        salary
count   4.000000      4.000000
mean   38.500000  73750.000000
std    12.871156   4787.135539
min    24.000000  70000.000000
25%    32.250000  70000.000000
50%    37.500000  72500.000000
75%    43.750000  76250.000000
max    55.000000  80000.000000

In [69]:
df["name"]

0      alice
1    charlie
2      david
3        bob
Name: name, dtype: str

In [70]:
df[["name", "salary", "city"]]

      name  salary     city
0    alice   70000      NYC
1  charlie   75000       LA
2    david   80000      NYC
3      bob   70000  chicago

In [71]:

df.iloc[0,3]

np.int64(70000)

In [72]:
df.loc[1,'salary']

np.int64(75000)

In [73]:
df['bonus'] = df['salary'] * 0.1

In [74]:
df

      name  age     city  salary   bonus
0    alice   35      NYC   70000  7000.0
1  charlie   24       LA   75000  7500.0
2    david   55      NYC   80000  8000.0
3      bob   40  chicago   70000  7000.0

In [75]:
df = df.drop(columns=['bonus'])

In [76]:
df

      name  age     city  salary
0    alice   35      NYC   70000
1  charlie   24       LA   75000
2    david   55      NYC   80000
3      bob   40  chicago   70000

In [77]:
df = df.rename(columns={'name': 'emp'})

In [78]:
df

       emp  age     city  salary
0    alice   35      NYC   70000
1  charlie   24       LA   75000
2    david   55      NYC   80000
3      bob   40  chicago   70000

Filtering

In [79]:
df[df['salary' ]>= 70000]

       emp  age     city  salary
0    alice   35      NYC   70000
1  charlie   24       LA   75000
2    david   55      NYC   80000
3      bob   40  chicago   70000

Multiple condition

In [80]:
df[(df['salary'] >= 70000) &(df['city'] == 'NYC') ] # Using AND ,"&"

     emp  age city  salary
0  alice   35  NYC   70000
2  david   55  NYC   80000

In [81]:
df[(df['salary'] >= 80000) | (df['city'] == 'LA')] # Using OR, "|"

       emp  age city  salary
1  charlie   24   LA   75000
2    david   55  NYC   80000

In [82]:
df[~(df['city'] == 'NYC')] # Using NOT, "~"

       emp  age     city  salary
1  charlie   24       LA   75000
3      bob   40  chicago   70000

Handy filter methods

In [83]:
df[(df['city'].isin(['LA', 'chicago']))] # macth a  list

       emp  age     city  salary
1  charlie   24       LA   75000
3      bob   40  chicago   70000

In [84]:
df[(df['emp'].str.contains('a'))] #string contains

       emp  age city  salary
0    alice   35  NYC   70000
1  charlie   24   LA   75000
2    david   55  NYC   80000

In [85]:
df.query('salary > 70000 and city == "NYC"') # query stirng

     emp  age city  salary
2  david   55  NYC   80000

GroupBy

In [86]:
df.groupby('emp')['salary'].mean()

emp
alice      70000.0
bob        70000.0
charlie    75000.0
david      80000.0
Name: salary, dtype: float64

In [87]:
g = df.groupby('city') # Common aggregations
print(g['salary'].sum(),"\n")
print(g['salary'].mean(),"\n")
print(g['salary'].max(),"\n")
print(g['salary'].count(),"\n")
print(g['salary'].std(),"\n")

city
LA          75000
NYC        150000
chicago     70000
Name: salary, dtype: int64

city
LA         75000.0
NYC        75000.0
chicago    70000.0
Name: salary, dtype: float64

city
LA         75000
NYC        80000
chicago    70000
Name: salary, dtype: int64

city
LA         1
NYC        2
chicago    1
Name: salary, dtype: int64

city
LA                 NaN
NYC        7071.067812
chicago            NaN
Name: salary, dtype: float64

In [88]:
#Multiple aggregations
df.groupby('city').agg(
    avg_sal=('salary', 'mean'),
    headcount = ('emp', 'count'),
    max_sal = ('salary', 'max')
)

         avg_sal  headcount  max_sal
city
LA       75000.0          1    75000
NYC      75000.0          2    80000
chicago  70000.0          1    70000

In [89]:
df.groupby('city')['salary'].mean() # aggergate

df['city_avg'] = df.groupby('city')['salary'].transform('mean') # # transform → keeps original shape (row-aligned)
df['pct_of_ avg'] = df['salary'] / df['city_avg']
df

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

Merging

In [90]:
employees = pd.DataFrame({'emp_id':[1,2,3], 'name':['alice','charlie','david']})
salaries  = pd.DataFrame({'emp_id':[1,2,3],  'pay': [70000, 75000, 80000]})

In [91]:
pd.merge(employees, salaries, on='emp_id') # inner (default)

   emp_id     name    pay
0       1    alice  70000
1       2  charlie  75000
2       3    david  80000

In [92]:
pd.merge(employees, salaries , on='emp_id', how='left') # left

   emp_id     name    pay
0       1    alice  70000
1       2  charlie  75000
2       3    david  80000

In [93]:
pd.merge(employees, salaries , on='emp_id', how='outer') # outer

   emp_id     name    pay
0       1    alice  70000
1       2  charlie  75000
2       3    david  80000

In [94]:
pd.merge(employees, salaries , on='emp_id', how='right') # right

   emp_id     name    pay
0       1    alice  70000
1       2  charlie  75000
2       3    david  80000

In [95]:
pd.merge(employees, salaries ,  how='cross') # cross

   emp_id_x     name  emp_id_y    pay
0         1    alice         1  70000
1         1    alice         2  75000
2         1    alice         3  80000
3         2  charlie         1  70000
4         2  charlie         2  75000
5         2  charlie         3  80000
6         3    david         1  70000
7         3    david         2  75000
8         3    david         3  80000

In [96]:
pd.concat([employees, salaries]) # stack rows axis = 0

   emp_id     name      pay
0       1    alice      NaN
1       2  charlie      NaN
2       3    david      NaN
0       1      NaN  70000.0
1       2      NaN  75000.0
2       3      NaN  80000.0

In [97]:
pd.concat([employees, salaries], axis=1) # stack rows axis = 1

   emp_id     name  emp_id    pay
0       1    alice       1  70000
1       2  charlie       2  75000
2       3    david       3  80000

In [98]:
pd.concat([employees, salaries], ignore_index=True) # reset index after stacking

   emp_id     name      pay
0       1    alice      NaN
1       2  charlie      NaN
2       3    david      NaN
3       1      NaN  70000.0
4       2      NaN  75000.0
5       3      NaN  80000.0

In [99]:
pd.merge(employees , salaries, left_on='emp_id', right_on= 'pay')

Empty DataFrame
Columns: [emp_id_x, name, emp_id_y, pay]
Index: []

Resahping

In [100]:
df.pivot_table(
    values='salary',
    index='city',
    columns='age',
    aggfunc='mean',
    fill_value=0
)

age           24       35       40       55
city
LA       75000.0      0.0      0.0      0.0
NYC          0.0  70000.0      0.0  80000.0
chicago      0.0      0.0  70000.0      0.0

In [101]:
#Unpivots columns into rows. Great before plotting time-series.
df.melt(
    id_vars=['emp'],
    value_vars=['city', 'salary'],
    var_name='quarter',
    value_name='revenue'
)

       emp quarter  revenue
0    alice    city      NYC
1  charlie    city       LA
2    david    city      NYC
3      bob    city  chicago
4    alice  salary    70000
5  charlie  salary    75000
6    david  salary    80000
7      bob  salary    70000

In [102]:
df.stack() # columns → inner index level

0  emp               alice
   age                  35
   city                NYC
   salary            70000
   city_avg        75000.0
   pct_of_ avg    0.933333
1  emp             charlie
   age                  24
   city                 LA
   salary            75000
   city_avg        75000.0
   pct_of_ avg         1.0
2  emp               david
   age                  55
   city                NYC
   salary            80000
   city_avg        75000.0
   pct_of_ avg    1.066667
3  emp                 bob
   age                  40
   city            chicago
   salary            70000
   city_avg        70000.0
   pct_of_ avg         1.0
dtype: object

In [103]:
df.unstack() # inner index level → columns

emp          0       alice
             1     charlie
             2       david
             3         bob
age          0          35
             1          24
             2          55
             3          40
city         0         NYC
             1          LA
             2         NYC
             3     chicago
salary       0       70000
             1       75000
             2       80000
             3       70000
city_avg     0     75000.0
             1     75000.0
             2     75000.0
             3     70000.0
pct_of_ avg  0    0.933333
             1         1.0
             2    1.066667
             3         1.0
dtype: object

In [104]:
df.unstack(level=1) # specify level

emp          0       alice
             1     charlie
             2       david
             3         bob
age          0          35
             1          24
             2          55
             3          40
city         0         NYC
             1          LA
             2         NYC
             3     chicago
salary       0       70000
             1       75000
             2       80000
             3       70000
city_avg     0     75000.0
             1     75000.0
             2     75000.0
             3     70000.0
pct_of_ avg  0    0.933333
             1         1.0
             2    1.066667
             3         1.0
dtype: object

In [105]:
df.stack(level=0)

0  emp               alice
   age                  35
   city                NYC
   salary            70000
   city_avg        75000.0
   pct_of_ avg    0.933333
1  emp             charlie
   age                  24
   city                 LA
   salary            75000
   city_avg        75000.0
   pct_of_ avg         1.0
2  emp               david
   age                  55
   city                NYC
   salary            80000
   city_avg        75000.0
   pct_of_ avg    1.066667
3  emp                 bob
   age                  40
   city            chicago
   salary            70000
   city_avg        70000.0
   pct_of_ avg         1.0
dtype: object

Missing data

In [106]:
df.isna() # True were NaN

     emp    age   city  salary  city_avg  pct_of_ avg
0  False  False  False   False     False        False
1  False  False  False   False     False        False
2  False  False  False   False     False        False
3  False  False  False   False     False        False

In [107]:
df.isna().sum().sum()

np.int64(0)

In [108]:
df.notna()

    emp   age  city  salary  city_avg  pct_of_ avg
0  True  True  True    True      True         True
1  True  True  True    True      True         True
2  True  True  True    True      True         True
3  True  True  True    True      True         True

DROP

In [109]:
df.dropna() # drop rows with any NaN

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

In [110]:
df.dropna(how='all') # only if ALL columns are NaN

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

In [111]:
df.dropna(subset=['salary']) # check specific columns

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

FILL

In [117]:
# constant
df.fillna(0)
df['salary'].fillna(df['salary'].median())

0    70000
1    75000
2    80000
3    70000
Name: salary, dtype: int64

In [114]:
# forward-fill (previous valid)
df.ffill()

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

In [115]:
# back-fill (next valid)
df.bfill()

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

In [116]:
# interpolate
df['age'].interpolate()

0    35
1    24
2    55
3    40
Name: age, dtype: int64

In [ ]:
df.replace(-1, pd.NA) # treat -1 as missing

       emp  age     city  salary  city_avg  pct_of_ avg
0    alice   35      NYC   70000   75000.0     0.933333
1  charlie   24       LA   75000   75000.0     1.000000
2    david   55      NYC   80000   75000.0     1.066667
3      bob   40  chicago   70000   70000.0     1.000000

In [121]:
# multiple substitutions
df.replace({'city': {'NYC': 'New York City',
                      'LA': 'LOS Angeles'}})

       emp  age           city  salary  city_avg  pct_of_ avg
0    alice   35  New York City   70000   75000.0     0.933333
1  charlie   24    LOS Angeles   75000   75000.0     1.000000
2    david   55  New York City   80000   75000.0     1.066667
3      bob   40        chicago   70000   70000.0     1.000000