Reading CSV

In [46]:
import pandas as pd
# Method 1
df = pd.read_csv(r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\iris2.csv')

In [47]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [48]:
# Method 2
import csv

with open(r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\iris2.csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        print(row)

{'sepal_length': '5.1', 'sepal_width': '3.5', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.0', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.7', 'sepal_width': '3.2', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.6', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.9', 'petal_length': '1.7', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.4', 'petal_length': '1.4', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.4', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.4', 'sepal_width': '2.9', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.7', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.4', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.0', 'petal_length': '1.4', 'petal_width': '0.1', 'species': 'setosa'}
{'sepal_length': '4.3', 'sepal_width': '3.0', 'petal_length': '1.1', 'petal_width': '0.1', 'species': 'setosa'}
{'sepal_length': '5.8', 'sepal_width': '4.0', 'petal_length': '1.2', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.7', 'sepal_width': '4.4', 'petal_length': '1.5', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.9', 'petal_length': '1.3', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.5', 'petal_length': '1.4', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '5.7', 'sepal_width': '3.8', 'petal_length': '1.7', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.8', 'petal_length': '1.5', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.4', 'petal_length': '1.7', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.7', 'petal_length': '1.5', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.6', 'petal_length': '1.0', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.3', 'petal_length': '1.7', 'petal_width': '0.5', 'species': 'setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.4', 'petal_length': '1.9', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.0', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.4', 'petal_length': '1.6', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '5.2', 'sepal_width': '3.5', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.2', 'sepal_width': '3.4', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.7', 'sepal_width': '3.2', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.1', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.4', 'sepal_width': '3.4', 'petal_length': '1.5', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '5.2', 'sepal_width': '4.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'setosa'}
{'sepal_length': '5.5', 'sepal_width': '4.2', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.2', 'petal_length': '1.2', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.5', 'sepal_width': '3.5', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.9', 'sepal_width': '3.1', 'petal_length': '1.5', 'petal_width': '0.1', 'species': 'setosa'}
{'sepal_length': '4.4', 'sepal_width': '3.0', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.4', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.5', 'petal_length': '1.3', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '4.5', 'sepal_width': '2.3', 'petal_length': '1.3', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '4.4', 'sepal_width': '3.2', 'petal_length': '1.3', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.5', 'petal_length': '1.6', 'petal_width': '0.6', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.8', 'petal_length': '1.9', 'petal_width': '0.4', 'species': 'setosa'}
{'sepal_length': '4.8', 'sepal_width': '3.0', 'petal_length': '1.4', 'petal_width': '0.3', 'species': 'setosa'}
{'sepal_length': '5.1', 'sepal_width': '3.8', 'petal_length': '1.6', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '4.6', 'sepal_width': '3.2', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.3', 'sepal_width': '3.7', 'petal_length': '1.5', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '5.0', 'sepal_width': '3.3', 'petal_length': '1.4', 'petal_width': '0.2', 'species': 'setosa'}
{'sepal_length': '7.0', 'sepal_width': '3.2', 'petal_length': '4.7', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '6.4', 'sepal_width': '3.2', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '6.9', 'sepal_width': '3.1', 'petal_length': '4.9', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.3', 'petal_length': '4.0', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.5', 'sepal_width': '2.8', 'petal_length': '4.6', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.8', 'petal_length': '4.5', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.3', 'sepal_width': '3.3', 'petal_length': '4.7', 'petal_width': '1.6', 'species': 'versicolor'}
{'sepal_length': '4.9', 'sepal_width': '2.4', 'petal_length': '3.3', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '6.6', 'sepal_width': '2.9', 'petal_length': '4.6', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '5.2', 'sepal_width': '2.7', 'petal_length': '3.9', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '5.0', 'sepal_width': '2.0', 'petal_length': '3.5', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '5.9', 'sepal_width': '3.0', 'petal_length': '4.2', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '6.0', 'sepal_width': '2.2', 'petal_length': '4.0', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '6.1', 'sepal_width': '2.9', 'petal_length': '4.7', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '5.6', 'sepal_width': '2.9', 'petal_length': '3.6', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.7', 'sepal_width': '3.1', 'petal_length': '4.4', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '5.6', 'sepal_width': '3.0', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '4.1', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '6.2', 'sepal_width': '2.2', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '5.6', 'sepal_width': '2.5', 'petal_length': '3.9', 'petal_width': '1.1', 'species': 'versicolor'}
{'sepal_length': '5.9', 'sepal_width': '3.2', 'petal_length': '4.8', 'petal_width': '1.8', 'species': 'versicolor'}
{'sepal_length': '6.1', 'sepal_width': '2.8', 'petal_length': '4.0', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.3', 'sepal_width': '2.5', 'petal_length': '4.9', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '6.1', 'sepal_width': '2.8', 'petal_length': '4.7', 'petal_width': '1.2', 'species': 'versicolor'}
{'sepal_length': '6.4', 'sepal_width': '2.9', 'petal_length': '4.3', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.6', 'sepal_width': '3.0', 'petal_length': '4.4', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '6.8', 'sepal_width': '2.8', 'petal_length': '4.8', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '6.7', 'sepal_width': '3.0', 'petal_length': '5.0', 'petal_width': '1.7', 'species': 'versicolor'}
{'sepal_length': '6.0', 'sepal_width': '2.9', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.6', 'petal_length': '3.5', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.4', 'petal_length': '3.8', 'petal_width': '1.1', 'species': 'versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.4', 'petal_length': '3.7', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '3.9', 'petal_width': '1.2', 'species': 'versicolor'}
{'sepal_length': '6.0', 'sepal_width': '2.7', 'petal_length': '5.1', 'petal_width': '1.6', 'species': 'versicolor'}
{'sepal_length': '5.4', 'sepal_width': '3.0', 'petal_length': '4.5', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '6.0', 'sepal_width': '3.4', 'petal_length': '4.5', 'petal_width': '1.6', 'species': 'versicolor'}
{'sepal_length': '6.7', 'sepal_width': '3.1', 'petal_length': '4.7', 'petal_width': '1.5', 'species': 'versicolor'}
{'sepal_length': '6.3', 'sepal_width': '2.3', 'petal_length': '4.4', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '5.6', 'sepal_width': '3.0', 'petal_length': '4.1', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.5', 'petal_length': '4.0', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '5.5', 'sepal_width': '2.6', 'petal_length': '4.4', 'petal_width': '1.2', 'species': 'versicolor'}
{'sepal_length': '6.1', 'sepal_width': '3.0', 'petal_length': '4.6', 'petal_width': '1.4', 'species': 'versicolor'}
{'sepal_length': '5.8', 'sepal_width': '2.6', 'petal_length': '4.0', 'petal_width': '1.2', 'species': 'versicolor'}
{'sepal_length': '5.0', 'sepal_width': '2.3', 'petal_length': '3.3', 'petal_width': '1.0', 'species': 'versicolor'}
{'sepal_length': '5.6', 'sepal_width': '2.7', 'petal_length': '4.2', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '5.7', 'sepal_width': '3.0', 'petal_length': '4.2', 'petal_width': '1.2', 'species': 'versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.9', 'petal_length': '4.2', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.2', 'sepal_width': '2.9', 'petal_length': '4.3', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '5.1', 'sepal_width': '2.5', 'petal_length': '3.0', 'petal_width': '1.1', 'species': 'versicolor'}
{'sepal_length': '5.7', 'sepal_width': '2.8', 'petal_length': '4.1', 'petal_width': '1.3', 'species': 'versicolor'}
{'sepal_length': '6.3', 'sepal_width': '3.3', 'petal_length': '6.0', 'petal_width': '2.5', 'species': 'virginica'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '5.1', 'petal_width': '1.9', 'species': 'virginica'}
{'sepal_length': '7.1', 'sepal_width': '3.0', 'petal_length': '5.9', 'petal_width': '2.1', 'species': 'virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.9', 'petal_length': '5.6', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.5', 'sepal_width': '3.0', 'petal_length': '5.8', 'petal_width': '2.2', 'species': 'virginica'}
{'sepal_length': '7.6', 'sepal_width': '3.0', 'petal_length': '6.6', 'petal_width': '2.1', 'species': 'virginica'}
{'sepal_length': '4.9', 'sepal_width': '2.5', 'petal_length': '4.5', 'petal_width': '1.7', 'species': 'virginica'}
{'sepal_length': '7.3', 'sepal_width': '2.9', 'petal_length': '6.3', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.7', 'sepal_width': '2.5', 'petal_length': '5.8', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '7.2', 'sepal_width': '3.6', 'petal_length': '6.1', 'petal_width': '2.5', 'species': 'virginica'}
{'sepal_length': '6.5', 'sepal_width': '3.2', 'petal_length': '5.1', 'petal_width': '2.0', 'species': 'virginica'}
{'sepal_length': '6.4', 'sepal_width': '2.7', 'petal_length': '5.3', 'petal_width': '1.9', 'species': 'virginica'}
{'sepal_length': '6.8', 'sepal_width': '3.0', 'petal_length': '5.5', 'petal_width': '2.1', 'species': 'virginica'}
{'sepal_length': '5.7', 'sepal_width': '2.5', 'petal_length': '5.0', 'petal_width': '2.0', 'species': 'virginica'}
{'sepal_length': '5.8', 'sepal_width': '2.8', 'petal_length': '5.1', 'petal_width': '2.4', 'species': 'virginica'}
{'sepal_length': '6.4', 'sepal_width': '3.2', 'petal_length': '5.3', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '6.5', 'sepal_width': '3.0', 'petal_length': '5.5', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '7.7', 'sepal_width': '3.8', 'petal_length': '6.7', 'petal_width': '2.2', 'species': 'virginica'}
{'sepal_length': '7.7', 'sepal_width': '2.6', 'petal_length': '6.9', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '6.0', 'sepal_width': '2.2', 'petal_length': '5.0', 'petal_width': '1.5', 'species': 'virginica'}
{'sepal_length': '6.9', 'sepal_width': '3.2', 'petal_length': '5.7', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '5.6', 'sepal_width': '2.8', 'petal_length': '4.9', 'petal_width': '2.0', 'species': 'virginica'}
{'sepal_length': '7.7', 'sepal_width': '2.8', 'petal_length': '6.7', 'petal_width': '2.0', 'species': 'virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.7', 'petal_length': '4.9', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.3', 'petal_length': '5.7', 'petal_width': '2.1', 'species': 'virginica'}
{'sepal_length': '7.2', 'sepal_width': '3.2', 'petal_length': '6.0', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.2', 'sepal_width': '2.8', 'petal_length': '4.8', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.1', 'sepal_width': '3.0', 'petal_length': '4.9', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.4', 'sepal_width': '2.8', 'petal_length': '5.6', 'petal_width': '2.1', 'species': 'virginica'}
{'sepal_length': '7.2', 'sepal_width': '3.0', 'petal_length': '5.8', 'petal_width': '1.6', 'species': 'virginica'}
{'sepal_length': '7.4', 'sepal_width': '2.8', 'petal_length': '6.1', 'petal_width': '1.9', 'species': 'virginica'}
{'sepal_length': '7.9', 'sepal_width': '3.8', 'petal_length': '6.4', 'petal_width': '2.0', 'species': 'virginica'}
{'sepal_length': '6.4', 'sepal_width': '2.8', 'petal_length': '5.6', 'petal_width': '2.2', 'species': 'virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.8', 'petal_length': '5.1', 'petal_width': '1.5', 'species': 'virginica'}
{'sepal_length': '6.1', 'sepal_width': '2.6', 'petal_length': '5.6', 'petal_width': '1.4', 'species': 'virginica'}
{'sepal_length': '7.7', 'sepal_width': '3.0', 'petal_length': '6.1', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '6.3', 'sepal_width': '3.4', 'petal_length': '5.6', 'petal_width': '2.4', 'species': 'virginica'}
{'sepal_length': '6.4', 'sepal_width': '3.1', 'petal_length': '5.5', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.0', 'sepal_width': '3.0', 'petal_length': '4.8', 'petal_width': '1.8', 'species': 'virginica'}
{'sepal_length': '6.9', 'sepal_width': '3.1', 'petal_length': '5.4', 'petal_width': '2.1', 'species': 'virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.1', 'petal_length': '5.6', 'petal_width': '2.4', 'species': 'virginica'}
{'sepal_length': '6.9', 'sepal_width': '3.1', 'petal_length': '5.1', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '5.8', 'sepal_width': '2.7', 'petal_length': '5.1', 'petal_width': '1.9', 'species': 'virginica'}
{'sepal_length': '6.8', 'sepal_width': '3.2', 'petal_length': '5.9', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.3', 'petal_length': '5.7', 'petal_width': '2.5', 'species': 'virginica'}
{'sepal_length': '6.7', 'sepal_width': '3.0', 'petal_length': '5.2', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '6.3', 'sepal_width': '2.5', 'petal_length': '5.0', 'petal_width': '1.9', 'species': 'virginica'}
{'sepal_length': '6.5', 'sepal_width': '3.0', 'petal_length': '5.2', 'petal_width': '2.0', 'species': 'virginica'}
{'sepal_length': '6.2', 'sepal_width': '3.4', 'petal_length': '5.4', 'petal_width': '2.3', 'species': 'virginica'}
{'sepal_length': '5.9', 'sepal_width': '3.0', 'petal_length': '5.1', 'petal_width': '1.8', 'species': 'virginica'}

Writing CSV

In [49]:
# Panda Method
df.to_csv(r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\iris2.csv', index= False)
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [53]:
# csv module method
with open(r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\iris2.csv', 'w', newline='') as csvfile:
    fieldname =[' ', 'sepal_length', 'sepal_width', 'petal_length', 'petal_width','species'] 
    writer = csv.DictWriter(csvfile, fieldnames=fieldname)
    writer.writeheader()
    writer.writerow({' ':149, 'sepal_length':5.9, 'sepal_width': 3.1, 'petal_length':5.2, 'petal_width':1.9, 'species':'virginica'})

Writing Json

Reading Parquet

In [2]:
import pandas as pd
import pyarrow.parquet as pq
# Method 1

df = pd.read_parquet(
    r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\titanic_p.parquet',
    engine="pyarrow"
)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
#method 2
table = pq.read_table(r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\titanic_p.parquet')
df = table.to_pandas()
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Write Parquet

In [ ]:
#method 1
df.to_parquet(r'C:\Users\CHARVAK\OneDrive\Desktop\DataSets\titanic_p.parquet', index=False)